### ISSUE TITLE
Need a GHC 9.2.1 release

### ISSUE THREAD

**Issue by LeventErkok** [shayne-fletcher/ghc-lib-parser-ex#99]
Trying to compile with 9.2.1 fails:

```
Preprocessing library for ghc-lib-parser-ex-9.0.0.4..
Building library for ghc-lib-parser-ex-9.0.0.4..
[ 1 of 20] Compiling Language.Haskell.GhclibParserEx.Dump
[ 2 of 20] Compiling Language.Haskell.GhclibParserEx.Fixity

src/Language/Haskell/GhclibParserEx/Fixity.hs:213:11: error:
    Not in scope: type constructor or class ‘FixityDirection’
    |
213 | fixity :: FixityDirection -> Int -> [String] -> [(String, Fixity)]
    |           ^^^^^^^^^^^^^^^

src/Language/Haskell/GhclibParserEx/Fixity.hs:228:48: error:
    Not in scope: data constructor ‘Fixity’
    Perhaps you meant one of these:
      variable ‘fixity’ (line 214),
      variable ‘fdFixity’ (imported from GHC.Hs)
    |
228 |     f (L _ (SigD _ (FixSig _ (FixitySig _ ops (Fixity _ p dir))))) =
    |                                                ^^^^^^
```

**Comment by shayne-fletcher** [comment]
ghc-lib-parser-ex-9.2.0.0 was published this afternoon. please let me know how it goes with that

**Comment by LeventErkok** [comment]
Looks great! Thanks for the quick patch.
