### ISSUE TITLE
Failure to compile with GHC 8.4

### ISSUE THREAD

**Issue by ndmitchell** [shayne-fletcher/ghc-lib-parser-ex#39]
I get:

```
Failed to install ghc-lib-parser-8.10.1.20200324
Build log ( /home/travis/.cabal/logs/ghc-8.4.4/ghc-lib-parser-8.10.1.20200324-DD7WEZv1DLv8XvMI2yfjnH.log ):
cabal: Entering directory '/tmp/cabal-tmp-11429/ghc-lib-parser-8.10.1.20200324'
Configuring ghc-lib-parser-8.10.1.20200324...
Preprocessing library for ghc-lib-parser-8.10.1.20200324..
In file included from /usr/include/_G_config.h:15:0,
                 from /usr/include/libio.h:31,
                 from /usr/include/stdio.h:74,
                 from /opt/ghc/8.4.4/lib/ghc-8.4.4/include/rts/Flags.h:16,
                 from /opt/ghc/8.4.4/lib/ghc-8.4.4/include/Rts.h:191,
                 from InfoTable.hsc:8:
InfoTable.hsc: In function ‘main’:
/opt/ghc/8.4.4/lib/ghc-8.4.4/template-hsc.h:75:24: error: ‘struct StgInfoTable_’ has no member named ‘srt’
                 (long) offsetof (t, f));
                        ^
InfoTable.hsc:41:5: note: in expansion of macro ‘hsc_peek’
/opt/ghc/8.4.4/lib/ghc-8.4.4/template-hsc.h:79:24: error: ‘StgInfoTable {aka struct StgInfoTable_}’ has no member named ‘srt’
                 (long) offsetof (t, f));
                        ^
InfoTable.hsc:59:5: note: in expansion of macro ‘hsc_poke’
compiling dist/build/GHC/Exts/Heap/InfoTable_hsc_make.c failed (exit code 1)
```

From https://travis-ci.org/github/ndmitchell/hlint/jobs/668189975

Are we going to have to ditch GHC 8.4 support?

**Comment by ndmitchell** [comment]
Maybe we need ghc-parser-ex and ghc-lib-parser-ex as two separate libraries, one of which hardcodes GHC as a dependency, and one of which hardcodes ghc-lib-parser?

Does anyone else use ghc-lib-parser-ex? If not, one option would be to fold this back into hlint, and accept that GHC and Cabal just don't offer the necessary abstraction.

Alternatively, we could git submodule this, and vendor the code in, so HLint didn't depend on ghc-lib-parser-ex, but the code for it was still available separately as a separate library, but also used by hlint.

**Comment by shayne-fletcher** [comment]
> Are we going to have to ditch GHC 8.4 support?

ghc no longer supports bootstrapping with 8.4 as of `abdfcc65a0cfc0e2f3bc391d464d0ad5` (09/29/2019). The subsequent removal of CPP guards in https://gitlab.haskell.org/ghc/ghc/commit/795986aaf33e2ffc233836b86a92a77366c91db2
for 'InfoTable.hsc' break the compile. I guess you have forgotten - I did forewarn you of this a week or two back 🙂

**Comment by shayne-fletcher** [comment]
> Does anyone else use ghc-lib-parser-ex? 

I don't know explicitly but I have received indications that it does appear to be in use by some other projects.

**Comment by shayne-fletcher** [comment]
For the avoidance of all doubt,

> Configuring ghc-lib-parser-8.10.1.20200324...
> Preprocessing library for ghc-lib-parser-8.10.1.20200324..

Just checking you appreciate this is not a ghc-lib-parser-ex issue but rather a ghc-lib (actually a ghc one).

**Comment by ndmitchell** [comment]
OK, as expected!
